openvpn:
  image: 4km3/openvpn:latest
  ports:
    - "1194:1194/udp"
  cap_add:
    - NET_ADMIN
  devices:
    - "/dev/net/tun:/dev/net/tun"
  volumes:
    - ./openvpn-assets:/etc/openvpn/
  working_dir: /etc/openvpn
  command: --config /etc/openvpn/openvpn.conf
  net: host
  restart: always
