squid:
  image: 4km3/openvpn:latest
  ports:
    - "1194:1194/udp"
  cap_add:
    - NET_ADMIN
  volumes:
    - /dev/net/tun:/dev/net/tun
    - ./openvpn-assets:/etc/openvpn/
  working_dir: /etc/openvpn
  command: --config /etc/openvpn/openvpn.conf
  restart: always
